// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/orkestra.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message vide pour les requêtes sans paramètres
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_orkestra_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orkestra_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_orkestra_proto_rawDescGZIP(), []int{0}
}

// Le contrat pour un nœud, optimisé pour la communication gRPC
type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Uses          string                 `protobuf:"bytes,2,opt,name=Uses,proto3" json:"Uses,omitempty"`
	With          []byte                 `protobuf:"bytes,3,opt,name=With,proto3" json:"With,omitempty"` // Les paramètres, sérialisés en JSON
	Needs         []string               `protobuf:"bytes,4,rep,name=Needs,proto3" json:"Needs,omitempty"`
	Do            []*Node                `protobuf:"bytes,5,rep,name=Do,proto3" json:"Do,omitempty"`           // Pour les boucles, la récursion est gérée
	Retries       []byte                 `protobuf:"bytes,6,opt,name=Retries,proto3" json:"Retries,omitempty"` // La structure Retries, sérialisée en JSON
	OnFailure     []*Node                `protobuf:"bytes,7,rep,name=OnFailure,proto3" json:"OnFailure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_proto_orkestra_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orkestra_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_proto_orkestra_proto_rawDescGZIP(), []int{1}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetUses() string {
	if x != nil {
		return x.Uses
	}
	return ""
}

func (x *Node) GetWith() []byte {
	if x != nil {
		return x.With
	}
	return nil
}

func (x *Node) GetNeeds() []string {
	if x != nil {
		return x.Needs
	}
	return nil
}

func (x *Node) GetDo() []*Node {
	if x != nil {
		return x.Do
	}
	return nil
}

func (x *Node) GetRetries() []byte {
	if x != nil {
		return x.Retries
	}
	return nil
}

func (x *Node) GetOnFailure() []*Node {
	if x != nil {
		return x.OnFailure
	}
	return nil
}

// Le contrat pour le contexte d'exécution
type ExecutionContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TriggerData   []byte                 `protobuf:"bytes,1,opt,name=TriggerData,proto3" json:"TriggerData,omitempty"` // Sérialisé en JSON
	NodeOutputs   []byte                 `protobuf:"bytes,2,opt,name=NodeOutputs,proto3" json:"NodeOutputs,omitempty"` // Sérialisé en JSON
	Secrets       map[string]string      `protobuf:"bytes,3,rep,name=Secrets,proto3" json:"Secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CurrentItem   []byte                 `protobuf:"bytes,4,opt,name=CurrentItem,proto3" json:"CurrentItem,omitempty"` // Sérialisé en JSON
	FailureData   []byte                 `protobuf:"bytes,5,opt,name=FailureData,proto3" json:"FailureData,omitempty"` // Sérialisé en JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionContext) Reset() {
	*x = ExecutionContext{}
	mi := &file_proto_orkestra_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionContext) ProtoMessage() {}

func (x *ExecutionContext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orkestra_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionContext.ProtoReflect.Descriptor instead.
func (*ExecutionContext) Descriptor() ([]byte, []int) {
	return file_proto_orkestra_proto_rawDescGZIP(), []int{2}
}

func (x *ExecutionContext) GetTriggerData() []byte {
	if x != nil {
		return x.TriggerData
	}
	return nil
}

func (x *ExecutionContext) GetNodeOutputs() []byte {
	if x != nil {
		return x.NodeOutputs
	}
	return nil
}

func (x *ExecutionContext) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *ExecutionContext) GetCurrentItem() []byte {
	if x != nil {
		return x.CurrentItem
	}
	return nil
}

func (x *ExecutionContext) GetFailureData() []byte {
	if x != nil {
		return x.FailureData
	}
	return nil
}

// La requête pour exécuter un nœud
type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Context       *ExecutionContext      `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_proto_orkestra_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orkestra_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_proto_orkestra_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteRequest) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *ExecuteRequest) GetContext() *ExecutionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

// La réponse de l'exécution d'un nœud
type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []byte                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // Le résultat, sérialisé en JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_proto_orkestra_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orkestra_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_proto_orkestra_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

// La réponse de la fonction GetCapabilities
type GetCapabilitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uses          []string               `protobuf:"bytes,1,rep,name=uses,proto3" json:"uses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapabilitiesResponse) Reset() {
	*x = GetCapabilitiesResponse{}
	mi := &file_proto_orkestra_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesResponse) ProtoMessage() {}

func (x *GetCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orkestra_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_orkestra_proto_rawDescGZIP(), []int{5}
}

func (x *GetCapabilitiesResponse) GetUses() []string {
	if x != nil {
		return x.Uses
	}
	return nil
}

var File_proto_orkestra_proto protoreflect.FileDescriptor

const file_proto_orkestra_proto_rawDesc = "" +
	"\n" +
	"\x14proto/orkestra.proto\x12\x05proto\"\a\n" +
	"\x05Empty\"\xb6\x01\n" +
	"\x04Node\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x12\n" +
	"\x04Uses\x18\x02 \x01(\tR\x04Uses\x12\x12\n" +
	"\x04With\x18\x03 \x01(\fR\x04With\x12\x14\n" +
	"\x05Needs\x18\x04 \x03(\tR\x05Needs\x12\x1b\n" +
	"\x02Do\x18\x05 \x03(\v2\v.proto.NodeR\x02Do\x12\x18\n" +
	"\aRetries\x18\x06 \x01(\fR\aRetries\x12)\n" +
	"\tOnFailure\x18\a \x03(\v2\v.proto.NodeR\tOnFailure\"\x96\x02\n" +
	"\x10ExecutionContext\x12 \n" +
	"\vTriggerData\x18\x01 \x01(\fR\vTriggerData\x12 \n" +
	"\vNodeOutputs\x18\x02 \x01(\fR\vNodeOutputs\x12>\n" +
	"\aSecrets\x18\x03 \x03(\v2$.proto.ExecutionContext.SecretsEntryR\aSecrets\x12 \n" +
	"\vCurrentItem\x18\x04 \x01(\fR\vCurrentItem\x12 \n" +
	"\vFailureData\x18\x05 \x01(\fR\vFailureData\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"d\n" +
	"\x0eExecuteRequest\x12\x1f\n" +
	"\x04node\x18\x01 \x01(\v2\v.proto.NodeR\x04node\x121\n" +
	"\acontext\x18\x02 \x01(\v2\x17.proto.ExecutionContextR\acontext\")\n" +
	"\x0fExecuteResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result\"-\n" +
	"\x17GetCapabilitiesResponse\x12\x12\n" +
	"\x04uses\x18\x01 \x03(\tR\x04uses2\x89\x01\n" +
	"\fNodeExecutor\x128\n" +
	"\aExecute\x12\x15.proto.ExecuteRequest\x1a\x16.proto.ExecuteResponse\x12?\n" +
	"\x0fGetCapabilities\x12\f.proto.Empty\x1a\x1e.proto.GetCapabilitiesResponseB\x10Z\x0eorkestra/protob\x06proto3"

var (
	file_proto_orkestra_proto_rawDescOnce sync.Once
	file_proto_orkestra_proto_rawDescData []byte
)

func file_proto_orkestra_proto_rawDescGZIP() []byte {
	file_proto_orkestra_proto_rawDescOnce.Do(func() {
		file_proto_orkestra_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_orkestra_proto_rawDesc), len(file_proto_orkestra_proto_rawDesc)))
	})
	return file_proto_orkestra_proto_rawDescData
}

var file_proto_orkestra_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_orkestra_proto_goTypes = []any{
	(*Empty)(nil),                   // 0: proto.Empty
	(*Node)(nil),                    // 1: proto.Node
	(*ExecutionContext)(nil),        // 2: proto.ExecutionContext
	(*ExecuteRequest)(nil),          // 3: proto.ExecuteRequest
	(*ExecuteResponse)(nil),         // 4: proto.ExecuteResponse
	(*GetCapabilitiesResponse)(nil), // 5: proto.GetCapabilitiesResponse
	nil,                             // 6: proto.ExecutionContext.SecretsEntry
}
var file_proto_orkestra_proto_depIdxs = []int32{
	1, // 0: proto.Node.Do:type_name -> proto.Node
	1, // 1: proto.Node.OnFailure:type_name -> proto.Node
	6, // 2: proto.ExecutionContext.Secrets:type_name -> proto.ExecutionContext.SecretsEntry
	1, // 3: proto.ExecuteRequest.node:type_name -> proto.Node
	2, // 4: proto.ExecuteRequest.context:type_name -> proto.ExecutionContext
	3, // 5: proto.NodeExecutor.Execute:input_type -> proto.ExecuteRequest
	0, // 6: proto.NodeExecutor.GetCapabilities:input_type -> proto.Empty
	4, // 7: proto.NodeExecutor.Execute:output_type -> proto.ExecuteResponse
	5, // 8: proto.NodeExecutor.GetCapabilities:output_type -> proto.GetCapabilitiesResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_orkestra_proto_init() }
func file_proto_orkestra_proto_init() {
	if File_proto_orkestra_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_orkestra_proto_rawDesc), len(file_proto_orkestra_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_orkestra_proto_goTypes,
		DependencyIndexes: file_proto_orkestra_proto_depIdxs,
		MessageInfos:      file_proto_orkestra_proto_msgTypes,
	}.Build()
	File_proto_orkestra_proto = out.File
	file_proto_orkestra_proto_goTypes = nil
	file_proto_orkestra_proto_depIdxs = nil
}
