// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0--rc2
// source: proto/orkestra.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeExecutor_Execute_FullMethodName         = "/proto.NodeExecutor/Execute"
	NodeExecutor_GetCapabilities_FullMethodName = "/proto.NodeExecutor/GetCapabilities"
)

// NodeExecutorClient is the client API for NodeExecutor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Le service gRPC que chaque plugin doit implémenter
type NodeExecutorClient interface {
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	GetCapabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error)
}

type nodeExecutorClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeExecutorClient(cc grpc.ClientConnInterface) NodeExecutorClient {
	return &nodeExecutorClient{cc}
}

func (c *nodeExecutorClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, NodeExecutor_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeExecutorClient) GetCapabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCapabilitiesResponse)
	err := c.cc.Invoke(ctx, NodeExecutor_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeExecutorServer is the server API for NodeExecutor service.
// All implementations must embed UnimplementedNodeExecutorServer
// for forward compatibility.
//
// Le service gRPC que chaque plugin doit implémenter
type NodeExecutorServer interface {
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	GetCapabilities(context.Context, *Empty) (*GetCapabilitiesResponse, error)
	mustEmbedUnimplementedNodeExecutorServer()
}

// UnimplementedNodeExecutorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeExecutorServer struct{}

func (UnimplementedNodeExecutorServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedNodeExecutorServer) GetCapabilities(context.Context, *Empty) (*GetCapabilitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedNodeExecutorServer) mustEmbedUnimplementedNodeExecutorServer() {}
func (UnimplementedNodeExecutorServer) testEmbeddedByValue()                      {}

// UnsafeNodeExecutorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeExecutorServer will
// result in compilation errors.
type UnsafeNodeExecutorServer interface {
	mustEmbedUnimplementedNodeExecutorServer()
}

func RegisterNodeExecutorServer(s grpc.ServiceRegistrar, srv NodeExecutorServer) {
	// If the following call pancis, it indicates UnimplementedNodeExecutorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeExecutor_ServiceDesc, srv)
}

func _NodeExecutor_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeExecutorServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeExecutor_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeExecutorServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeExecutor_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeExecutorServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeExecutor_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeExecutorServer).GetCapabilities(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeExecutor_ServiceDesc is the grpc.ServiceDesc for NodeExecutor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeExecutor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.NodeExecutor",
	HandlerType: (*NodeExecutorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _NodeExecutor_Execute_Handler,
		},
		{
			MethodName: "GetCapabilities",
			Handler:    _NodeExecutor_GetCapabilities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/orkestra.proto",
}
